version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi  
    ports:
      - "8000:80"  
    # networks:
    #   - app-network

  react:
    build:
      context: ./co2-prediction
    ports:
      - "3000:3000"  
    # networks:
    #   - app-network

# networks:
#   app-network:
#     driver: bridge
